DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS todo_lists CASCADE;

DROP TABLE IF EXISTS users_list CASCADE;

DROP TABLE IF EXISTS todo_items CASCADE;

DROP TABLE IF EXISTS lists_items CASCADE;
